name: TYPO3 14 Tests

on: [ push, pull_request ]
#on:
#  push:
#    branches: [ main, develop ]
#  pull_request:
#    branches: [ main, develop ]

jobs:
  acceptance:
    name: Acceptance Tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TYPO3 14 dependencies
        run: |
          mkdir -p .Build/.cache
          echo "start installing deps"
          sudo chmod -R 777 .Build/
          sudo chmod -R 777 .
          Build/Scripts/runTests.sh -p ${{ matrix.php }} -s composer -e "require typo3/cms-core:^14.0 --no-progress --no-interaction"
          echo "DONE installing deps"
          sudo chmod -R 777 .Build/
          mkdir -p .Build/public/typo3temp/var/transien
          sudo chmod -R 777 .
          sudo chmod -R 777 .Build/
          Build/Scripts/runTests.sh -s acceptance -p ${{ matrix.php }} -t 14

